-- Job Description Pipeline - Supabase Database Setup
-- Run this SQL in your Supabase project's SQL editor

-- Create the job_extractions table
CREATE TABLE IF NOT EXISTS job_extractions (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  role VARCHAR(255),
  skills TEXT[],
  seniority VARCHAR(50),
  location VARCHAR(255),
  salary VARCHAR(255),
  raw_jd TEXT,
  source VARCHAR(255),
  processed_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_job_extractions_role 
  ON job_extractions(role);

CREATE INDEX IF NOT EXISTS idx_job_extractions_created_at 
  ON job_extractions(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_job_extractions_seniority 
  ON job_extractions(seniority);

CREATE INDEX IF NOT EXISTS idx_job_extractions_location 
  ON job_extractions(location);

-- Enable Row Level Security (RLS) for security (optional but recommended)
ALTER TABLE job_extractions ENABLE ROW LEVEL SECURITY;

-- Create a policy to allow all operations (for development)
-- In production, implement stricter policies
CREATE POLICY "Allow all operations for now" ON job_extractions
  FOR ALL
  USING (true)
  WITH CHECK (true);

-- Optional: Create a view for recently processed jobs
CREATE OR REPLACE VIEW recent_extractions AS
  SELECT 
    id,
    role,
    skills,
    seniority,
    location,
    salary,
    source,
    created_at
  FROM job_extractions
  ORDER BY created_at DESC
  LIMIT 100;

-- Optional: Create a view for statistics
CREATE OR REPLACE VIEW extraction_stats AS
  SELECT 
    COUNT(*) as total_extractions,
    COUNT(DISTINCT role) as unique_roles,
    COUNT(DISTINCT seniority) as seniority_levels,
    COUNT(DISTINCT location) as unique_locations,
    MAX(created_at) as last_extraction,
    MIN(created_at) as first_extraction
  FROM job_extractions;

-- Optional: Create a function to get skills breakdown
CREATE OR REPLACE FUNCTION get_skills_breakdown()
RETURNS TABLE (skill TEXT, count BIGINT) AS $$
  SELECT 
    skill,
    COUNT(*) as count
  FROM job_extractions, 
  LATERAL UNNEST(skills) as skill
  WHERE skills IS NOT NULL
  GROUP BY skill
  ORDER BY count DESC
$$ LANGUAGE SQL;

-- Grant access (adjust as needed for your setup)
GRANT SELECT, INSERT, UPDATE ON job_extractions TO authenticated;
GRANT SELECT ON recent_extractions TO authenticated;
GRANT SELECT ON extraction_stats TO authenticated;

-- Verify setup
SELECT 'job_extractions table created successfully' as status;
SELECT COUNT(*) as total_records FROM job_extractions;
